<?php
/**
 * This file is part of Oyst_Oyst for Magento.
 *
 * @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 * @author Oyst <dev@oyst.com> <@oystcompany>
 * @category Oyst
 * @package Oyst_Oyst
 * @copyright Copyright (c) 2017 Oyst (http://www.oyst.com)
 */
?>
<?php
/**
 * @see Oyst_Oyst_Block_Form_Freepay
 */
?>
<img class="freepay-payment-method-icon v-middle" src="<?php echo $this->getSkinUrl('images/oyst/creditcard.png'); ?>" width="auto" height="auto" alt="<?php echo $this->getPaymentMethodLabel(); ?>" border="0"/>
