sudo: false
language: php

php:
  - 5.3
  #- 5.4
  #- 5.5
  #- 5.6
  #- 7.0

matrix:
  fast_finish: true
  #allow_failures:
  #  - php: 5.6
  exclude:
    # Newer Magento versions uses newer PHP versions
    - php: 5.3
      env: MAGENTO_VERSION="magento-mirror-1.9.3.2"
    # Old Magento Versions are not officially supported to run with PHP 5.5
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    # Old Magento Versions are not officially supported to run with PHP 5.6
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.8.1.0"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.0.1"
    # Old Magento Versions are not officially supported to run with PHP 7.0
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.8.1.0"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.0.1"

env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - TEST_BASEDIR=.modman/oyst-magento/app/code/community/Oyst/Oyst/Test
  matrix:
    - MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - MAGENTO_VERSION="magento-mirror-1.7.0.2"
    - MAGENTO_VERSION="magento-mirror-1.8.1.0"
    - MAGENTO_VERSION="magento-mirror-1.9.3.1"

install:
  - composer install --no-interaction
  - phpenv rehash

script:
  - mkdir -p build/logs
  - curl --retry 2 --retry-delay 5 -f -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
  - ./vendor/bin/phpcs --standard=PSR2 .modman/oyst-magento/ || true

notifications:
  email:
    on_success: always
    on_failure: always
