<div class='content-header'>
    <table cellspacing='0'>
        <tbody>
            <tr>
                <td><h3 class='head-dashboard'><?php echo Mage::helper('oyst_oyst')->__('Actions'); ?></h3></td>
            </tr>
        </tbody>
    </table>
</div>

<div id='action-button-container'>
    <p><?php echo Mage::helper('oyst_oyst')->__("To sync Catalog products with Oyst, click Here : ") ?></p>
    <button onclick="goToThis('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/oyst_catalog/sync') ?>');" type='submit' class='scalable task' style=''>
        <span> <span> <span><?php echo Mage::helper('oyst_oyst')->__('Oyst product sync')?></span>
        </span>
        </span>
    </button>
    <br /> <br /> <br />
</div>

<script type='text/javascript'>
function goToThis(url) {
    Element.show('loading-mask');
    window.location.href = url;
    //Element.hide('loading-mask');
};
</script>